<?php

/**
 * ProcessWire Language Field Tabs
 *
 * Organizes Lagnuage Fields into tabs for a cleaner easier to use interface
 * 
 * ProcessWire 2.x 
 * Copyright (C) 2011 by Ryan Cramer 
 * Licensed under GNU/GPL v2, see LICENSE.TXT
 * 
 *
 */

class LanguageFieldTabs extends WireData implements Module {


	public static function getModuleInfo() {

		return array(

			'title' => 'Language Field Tabs',
			'version' => 124,
			'summary' => 'Organizes Lagnuage Fields into tabs for a cleaner easier to use interface',
			'href' => '',
			'singular' => true,
			'autoload' => true,
		);
	}

	public function init() {
		$this->addHookAfter('ProcessPageEdit::execute', $this, 'loadTabs');
	}

	public function loadTabs(){
		$this->config->scripts->append($this->config->urls->LanguageFieldTabs . "LanguageFieldTabs.js");
		$this->config->styles->append($this->config->urls->LanguageFieldTabs . "LanguageFieldTabs.css");
	}
}