<?php

/**
 * ProcessWire Language Field Tabs
 *
 * Organizes Language Fields into tabs for a cleaner easier to use interface
 *
 * By Adamspruijt, Copyright 2013
 * 
 * For ProcessWire 2.x 
 * Copyright (C) 2013 by Ryan Cramer 
 * Licensed under GNU/GPL v2, see LICENSE.TXT
 * 
 *
 */

class LanguageFieldTabs extends WireData implements Module {

	public static function getModuleInfo() {

		return array(

			'title' => 'Language Field Tabs',
			'version' => 107,
			'summary' => 'Organizes Language Fields into tabs for a cleaner easier to use interface',
			'author' => 'adamspruijt', 
			'href' => '',
			'singular' => true,
			'autoload' => true,
		);
	}

	public function init() { }

	public function ready() {
		if($this->page->template != 'admin') return;

		$this->addHookAfter('ProcessPageEdit::execute', $this, 'loadTabs');
		$this->addHookAfter('Process::executeEdit', $this, 'loadTabs');

		$settings = array('title' => $this->_('Expand Language Tabs')); 
		$this->config->js('LanguageFieldTabs', $settings); 
	}

	public function loadTabs(){
		$this->config->scripts->add($this->config->urls->LanguageFieldTabs . "LanguageFieldTabs.js");
		$this->config->styles->add($this->config->urls->LanguageFieldTabs . "LanguageFieldTabs.css");
	}
}
